if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    set(CMAKE_OSX_SYSROOT macosx CACHE STRING "macOS SDK" FORCE)
    foreach(language C CXX OBJCXX)
        if(language STREQUAL "C")
            set(compiler clang)
        else()
            set(compiler clang++)
        endif()
        set(CMAKE_${language}_COMPILER "/opt/homebrew/opt/llvm/bin/${compiler}" CACHE FILEPATH "LLVM compiler" FORCE)
    endforeach()
endif()
