if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "ExtractMetalSource requires INPUT and OUTPUT")
endif()

file(READ "${INPUT}" source)
set(begin_marker "constexpr const char *Source = R\"metal(\n")
set(end_marker "\n)metal\";")
string(FIND "${source}" "${begin_marker}" begin)
string(FIND "${source}" "${end_marker}" end)
if(begin EQUAL -1 OR end EQUAL -1 OR end LESS begin)
    message(FATAL_ERROR "Finite-cell Metal source markers were not found in ${INPUT}")
endif()
string(LENGTH "${begin_marker}" marker_length)
math(EXPR begin "${begin} + ${marker_length}")
math(EXPR length "${end} - ${begin}")
string(SUBSTRING "${source}" ${begin} ${length} metal_source)
file(WRITE "${OUTPUT}" "${metal_source}\n")
