if(NOT DEFINED SOURCE OR NOT DEFINED OUTPUT OR NOT DEFINED LIBRARY)
    message(FATAL_ERROR "PrepareMetalPipelineScript requires SOURCE, OUTPUT, and LIBRARY")
endif()

file(READ "${SOURCE}" source)
string(REGEX MATCHALL "pipeline[(][@][\"][A-Za-z0-9]+[\"][)]" calls "${source}")
set(pipelines)
foreach(call IN LISTS calls)
    string(REGEX REPLACE "pipeline[(][@][\"]([A-Za-z0-9]+)[\"][)]" "\\1" function "${call}")
    list(APPEND pipelines "    {\"compute_function\": \"alias:FastFEMFiniteCell#${function}\", \"threadgroup_size_is_multiple_of_thread_execution_width\": false, \"max_total_threads_per_threadgroup\": 0, \"max_call_stack_depth\": 1, \"support_indirect_command_buffers\": false, \"support_adding_binary_functions\": false}")
endforeach()
list(REMOVE_DUPLICATES pipelines)
list(LENGTH pipelines pipeline_count)
if(NOT pipeline_count)
    message(FATAL_ERROR "No finite-cell pipeline construction calls were found in ${SOURCE}")
endif()
list(JOIN pipelines ",\n" pipelines)
file(WRITE "${OUTPUT}" "{\n  \"version\": {\"major\": 0, \"minor\": 3, \"sub_minor\": 0},\n  \"generator\": \"MetalFramework\",\n  \"libraries\": {\"paths\": [{\"label\": \"FastFEMFiniteCell\", \"path\": \"${LIBRARY}\"}]},\n  \"pipelines\": {\"compute_pipelines\": [\n${pipelines}\n  ]},\n  \"functions\": {}\n}\n")
